seed: 42
exp_dir: exps/ft/ft_0331
atom_features: 167
frag_features: 167
edge_features: 17

pretrain:
  chkpoint_name: exps/pt/pvkp_0331/pt.pt
  emb_dim: 128       # ✅ 必须和训练预训练模型时一致
  num_layer: 6       # ✅ 必须和训练预训练模型时一致
  drop_ratio: 0.15

finetune:
  train:  { path: finetune_data/perovskite_pkl/train.pkl }
  val:    { path: finetune_data/perovskite_pkl/val.pkl }
  test:   { path: finetune_data/perovskite_pkl/test.pkl }
  batch_size: 128
  lr: 0.00001
  n_epochs: 1000
  es_patience: 200
  chkpoint_name: exps/ft/test_0331/finetune_gcn.pt
  loss: mse          # mse / cel / bce
  target_type: regr   # regr / cls
  scale_y: false
  use_schedular: false
  model:
    n_classes: 1
    num_layer: 6
    drop_ratio: 0.3
    emb_dim: 128
    h1: 512
    h2: 256
    h3: 128
    h4: 64
    act: relu
    fthead: linear
